### ISSUE TITLE
R-CMD-check error for Windows

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/kmeaningfulR#49]
The continuous integration actions performed in `R-CMD-check.yaml`  generate an error when running R-CMD-check on a windows-latest OS. This is a known error related to the `qpdf` package. 
My personal computer is Windows and it passes on that without problem.

For more info:   https://community.rstudio.com/t/qpdf-is-needed-error-package/75485 

As a result I have commented out the windows line from `R-CMD-check.yaml` (see below). I can be put back when the qpdf problem is resolved by the people responsible. This is the solution proposed by Tiffany.

```
    strategy:
      fail-fast: false
      matrix:
        config:
          # An upstream problem related to qpdf is causing the windows test to fail.
          # - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
```
